// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrinudnaNaplata.Data;

#nullable disable

namespace PrinudnaNaplata.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260503142949_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PrinudnaNaplata.Domain.Duznik", b =>
                {
                    b.Property<int>("DuznikID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DuznikID"));

                    b.Property<string>("Adresa")
                        .HasMaxLength(1023)
                        .HasColumnType("nvarchar(1023)");

                    b.Property<string>("BrojeviRacuna")
                        .HasMaxLength(511)
                        .HasColumnType("nvarchar(511)");

                    b.Property<string>("Ime")
                        .HasMaxLength(1023)
                        .HasColumnType("nvarchar(1023)");

                    b.Property<string>("JMBG")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LicniBroj")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Mjesto")
                        .HasMaxLength(1023)
                        .HasColumnType("nvarchar(1023)");

                    b.Property<string>("Nekretnina")
                        .HasMaxLength(511)
                        .HasColumnType("nvarchar(511)");

                    b.Property<bool>("Nepoznat")
                        .HasColumnType("bit");

                    b.Property<bool>("Oznacen")
                        .HasColumnType("bit");

                    b.Property<bool>("Penzioner")
                        .HasColumnType("bit");

                    b.Property<bool?>("PravnoLice")
                        .HasColumnType("bit");

                    b.Property<string>("Prebivaliste")
                        .HasMaxLength(1023)
                        .HasColumnType("nvarchar(1023)");

                    b.Property<int?>("PreduzeceID")
                        .HasColumnType("int");

                    b.Property<string>("RegBr")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Reon")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("Umro")
                        .HasColumnType("bit");

                    b.Property<string>("Vozila")
                        .HasMaxLength(1023)
                        .HasColumnType("nvarchar(1023)");

                    b.Property<string>("ZavedenKodPov")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DuznikID");

                    b.HasIndex("PreduzeceID");

                    b.ToTable("Duznici");
                });

            modelBuilder.Entity("PrinudnaNaplata.Domain.Klijent", b =>
                {
                    b.Property<int>("KlijentID")
                        .HasColumnType("int");

                    b.Property<string>("Adresa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Adresa2")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("DodajPDVNaAdvTarifu")
                        .HasColumnType("bit");

                    b.Property<string>("Dokaz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grad")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Naziv")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PDV")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("PDVStopa")
                        .HasColumnType("decimal(15,3)");

                    b.Property<string>("PIB")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PostanskiBroj")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PozvatiSeNa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Racun")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Valuta")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Zemlja")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("KlijentID");

                    b.ToTable("Klijenti");
                });

            modelBuilder.Entity("PrinudnaNaplata.Domain.KontniPlan", b =>
                {
                    b.Property<string>("KontoBroj")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Naziv")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("KontoBroj");

                    b.ToTable("KontniPlan");
                });

            modelBuilder.Entity("PrinudnaNaplata.Domain.Partija", b =>
                {
                    b.Property<long>("PartijaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PartijaID"));

                    b.Property<decimal?>("ATPoPrigovoru")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal?>("AdvTarifa")
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("BrojPartije")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal?>("DodatniAT")
                        .HasColumnType("decimal(15,2)");

                    b.Property<bool>("DodatnoFakturisati")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DonetoDana")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DostavaUredna")
                        .HasColumnType("bit");

                    b.Property<bool>("DrugostepenaPresuda")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DrugostepenaPresudaDatum")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DugDo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DugOd")
                        .HasColumnType("datetime2");

                    b.Property<int>("DuznikID")
                        .HasColumnType("int");

                    b.Property<bool>("Fakturisano")
                        .HasColumnType("bit");

                    b.Property<decimal?>("FakturisanoProcenat")
                        .HasColumnType("decimal(15,2)");

                    b.Property<bool>("Fakturisati")
                        .HasColumnType("bit");

                    b.Property<bool>("FakturisatiSaPDV")
                        .HasColumnType("bit");

                    b.Property<bool>("Hipoteka")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("HipotekaDatum")
                        .HasColumnType("datetime2");

                    b.Property<string>("IVb")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("IpvBroj")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal?>("IznosDuga")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal?>("IznosPoPrigovoru")
                        .HasColumnType("decimal(15,2)");

                    b.Property<bool>("IzvrsenjePoPresudi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("IzvrsnoDana")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("IzvrsnoResenjeDatum")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IzvrsnoResenjeSuda")
                        .HasColumnType("bit");

                    b.Property<bool>("JavnaObjava")
                        .HasColumnType("bit");

                    b.Property<int>("KlijentID")
                        .HasColumnType("int");

                    b.Property<string>("MalBroj")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("Mrtav")
                        .HasColumnType("bit");

                    b.Property<string>("Napomena")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("NeFakturisati")
                        .HasColumnType("bit");

                    b.Property<bool>("NemaPokretneImovine")
                        .HasColumnType("bit");

                    b.Property<bool>("Obustavljen")
                        .HasColumnType("bit");

                    b.Property<bool>("Odbacen")
                        .HasColumnType("bit");

                    b.Property<bool>("Odbijen")
                        .HasColumnType("bit");

                    b.Property<bool>("Odlaganje")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("OdlaganjeDo")
                        .HasColumnType("datetime2");

                    b.Property<string>("Pb")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("Platio")
                        .HasColumnType("bit");

                    b.Property<decimal?>("PlatioIznos")
                        .HasColumnType("decimal(15,2)");

                    b.Property<bool>("PlatioOsnovniDug")
                        .HasColumnType("bit");

                    b.Property<bool>("Popis")
                        .HasColumnType("bit");

                    b.Property<bool>("Poravnanje")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PoravnanjeDatum")
                        .HasColumnType("datetime2");

                    b.Property<bool>("PoslatNaBlagajnu")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PredatoDana")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PredlNepImDonDana")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PredlNepImPredDana")
                        .HasColumnType("datetime2");

                    b.Property<bool>("PredlNepokImovina")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PredlPokrImDonDana")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PredlPokrImPredDana")
                        .HasColumnType("datetime2");

                    b.Property<bool>("PredlPokrImovina")
                        .HasColumnType("bit");

                    b.Property<bool>("Prekinut")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PresudaDatum")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Prigovor")
                        .HasColumnType("bit");

                    b.Property<bool>("PrigovorOdbacen")
                        .HasColumnType("bit");

                    b.Property<bool>("PrigovorOdbijen")
                        .HasColumnType("bit");

                    b.Property<bool>("PrigovorUsvojen")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PrimioDana")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Procena")
                        .HasColumnType("bit");

                    b.Property<decimal?>("ProcenatUspjeha")
                        .HasColumnType("decimal(15,2)");

                    b.Property<bool>("Prodaja")
                        .HasColumnType("bit");

                    b.Property<bool>("PrvostepenaPresuda")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PrvostepenaPresudaDatum")
                        .HasColumnType("datetime2");

                    b.Property<string>("RBroj")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ResenjeBroj")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("SpojenUIBroj")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("Storniran")
                        .HasColumnType("bit");

                    b.Property<long?>("Sud1ID")
                        .HasColumnType("bigint");

                    b.Property<long?>("SudID")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("SudskeTakse")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal?>("TaksaPoPrigovoru")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal?>("TrenutniDug")
                        .HasColumnType("decimal(15,2)");

                    b.Property<bool>("Uplatio")
                        .HasColumnType("bit");

                    b.Property<bool>("ZakljucakNalog")
                        .HasColumnType("bit");

                    b.Property<bool>("ZakljucakNalogNisuPostupili")
                        .HasColumnType("bit");

                    b.Property<bool>("Zakljucena")
                        .HasColumnType("bit");

                    b.Property<bool>("Zalba")
                        .HasColumnType("bit");

                    b.HasKey("PartijaID");

                    b.HasIndex("DuznikID");

                    b.HasIndex("KlijentID");

                    b.HasIndex("Sud1ID");

                    b.HasIndex("SudID");

                    b.ToTable("Partije");
                });

            modelBuilder.Entity("PrinudnaNaplata.Domain.PodrazumijevanaAdvokatskaTarifa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("KlijentID")
                        .HasColumnType("int");

                    b.Property<decimal?>("Tarifa")
                        .HasColumnType("decimal(15,2)");

                    b.Property<decimal?>("TarifaProcenat")
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("Id");

                    b.HasIndex("KlijentID");

                    b.ToTable("PodrazumijevaneAdvokatskeTarife");
                });

            modelBuilder.Entity("PrinudnaNaplata.Domain.PravaPristupaKlijent", b =>
                {
                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("KlijentID")
                        .HasColumnType("int");

                    b.Property<int?>("Izmjena")
                        .HasColumnType("int");

                    b.HasKey("UserName", "KlijentID");

                    b.HasIndex("KlijentID");

                    b.ToTable("PravaPristupaKlijent");
                });

            modelBuilder.Entity("PrinudnaNaplata.Domain.Preduzece", b =>
                {
                    b.Property<int>("PreduzeceID")
                        .HasColumnType("int");

                    b.Property<string>("Adresa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Banka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KontaktOsoba")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mjesto")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Napomena")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PIB")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Telefoni")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZiroRacun")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PreduzeceID");

                    b.ToTable("Preduzeca");
                });

            modelBuilder.Entity("PrinudnaNaplata.Domain.Sud", b =>
                {
                    b.Property<long>("SudID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SudID"));

                    b.Property<string>("KratakNaziv")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("KratakPuniNaziv")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Mjesto")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Naziv")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("SudID");

                    b.ToTable("Sudovi");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PrinudnaNaplata.Domain.Duznik", b =>
                {
                    b.HasOne("PrinudnaNaplata.Domain.Preduzece", null)
                        .WithMany()
                        .HasForeignKey("PreduzeceID")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("PrinudnaNaplata.Domain.Partija", b =>
                {
                    b.HasOne("PrinudnaNaplata.Domain.Duznik", null)
                        .WithMany()
                        .HasForeignKey("DuznikID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrinudnaNaplata.Domain.Klijent", null)
                        .WithMany()
                        .HasForeignKey("KlijentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrinudnaNaplata.Domain.Sud", null)
                        .WithMany()
                        .HasForeignKey("Sud1ID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PrinudnaNaplata.Domain.Sud", null)
                        .WithMany()
                        .HasForeignKey("SudID")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("PrinudnaNaplata.Domain.PodrazumijevanaAdvokatskaTarifa", b =>
                {
                    b.HasOne("PrinudnaNaplata.Domain.Klijent", null)
                        .WithMany()
                        .HasForeignKey("KlijentID")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("PrinudnaNaplata.Domain.PravaPristupaKlijent", b =>
                {
                    b.HasOne("PrinudnaNaplata.Domain.Klijent", null)
                        .WithMany()
                        .HasForeignKey("KlijentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserName")
                        .HasPrincipalKey("UserName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
