namespace PrinudnaNaplata.Models.Dtos.Case
{
    public record CaseFilterDto
    (
        string? BrzaPretraga,
        string? BrojPartije,
        string? ResenjeBroj, // searches IVb, Pb, MalBroj, IpvBroj, RBroj too
        string? ImeDuznika,
        string? NadlezniOrgan,
        DateTime? PredatoDanaOd,
        DateTime? PredatoDanaDo,
        DateTime? DonetoDanaOd,
        DateTime? DonetoDanaDo,
        decimal? UkupanDug,
        string? ZavedenKodPov,
        bool? PravnoLice,
        bool? JavnaObjava,
        bool? Odlaganje,
        DateTime? OdlaganjeDo,
        bool? Odbacen,
        bool? Prekinut,
        bool? Odbijen,
        bool? Obustavljen,
        bool? PrigovorUsvojen,
        bool? PrigovorOdbijen,
        bool? PrigovorOdbacen,
        bool? FakturisanoPovjeriocu,
        decimal? FakturisanoPovjeriocuProcenat,
        bool? Prigovor,
        bool? Popis,
        bool? Procjena,
        bool? Prodaja,
        bool? NemaPokretneImovine,
        bool? Zakljucena,
        bool? Mrtav,
        bool? Poravnanje,
        bool? IzvrsnoResenjeSuda,
        bool? PrvostepenaPresuda,
        bool? Zalba,
        bool? DrugostepenaPresuda,
        DateTime? IzvrsnoDanaOd,
        DateTime? IzvrsnoDanaDo,
        bool? ZakljucakNalog,
        bool? ZakljucakNalogNisuPostupili,
        bool? IzvrsenjePoPresudiResenju,
        bool? Uplatio,
        decimal? Platio,
        bool? Fakturisati,
        bool? NeFakturisati,
        bool? PredlPokrImovina,
        bool? PredlNepokImovina,
        bool? HipotekaKodKatastra,
        bool? Nekretnina,
        bool? Vozila,
        string? Zaposlen,
        bool? Penzioner,
        int PageNumber = 1,
        int PageSize = 10  
    );
}